services:
  - type: web
    name: smarterp-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: CORS_ORIGIN
        value: https://smart-erp-liard.vercel.app
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
      - key: DATABASE_URL
        value: "mongodb+srv://smartERP:YOUR_NEW_PASSWORD@cluster0.jdclnkg.mongodb.net/smarterp?retryWrites=true&w=majority"
